export const COMPANY = {
  name: 'Citatio',
  legalName: 'Citatio',
  url: 'https://citatio-geo.com',
  logo: 'https://citatio-geo.com/citatio_logo.png',
  locale: 'fr_FR',
  lang: 'French',
  description:
    'Citatio est un studio web qui crée des sites vitrines sur mesure pour les TPE, PME et indépendants, avec le référencement Google (SEO) et la visibilité sur l\'IA (GEO) en option, plus l\'hébergement, le nom de domaine et la maintenance.',
  shortDescription:
    'Studio web : sites vitrines sur mesure, avec SEO et visibilité IA (GEO) en option.',
  email: 'contact@citatio-geo.com',
  phone: '+33-7-67-47-83-72',
  phoneRaw: '+33767478372',
  phoneDisplay: '+33 7 67 47 83 72',
  address: {
    street: '1 rue de l\'Aven',
    city: 'La Chapelle-sur-Erdre',
    postalCode: '44240',
    country: 'FR',
  },
  priceRange: '€€',
  foundingYear: 2025,
  knowsAbout: [
    'Création de site vitrine',
    'Studio web',
    'Web design',
    'SEO',
    'Référencement Google',
    'Generative Engine Optimization',
    'GEO',
    'Visibilité IA',
    'Hébergement web',
  ],
  sameAs: [] as string[],
} as const;
