services:
  database:
    image: postgres:15-alpine
    container_name: citatio-db
    restart: always
    environment:
      POSTGRES_DB: citatio_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/db:/var/lib/postgresql/data

  backend:
    image: ghcr.io/mariusdev80/citatio/backend:latest
    container_name: citatio-back
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_NAME: citatio_db
      DB_USER: user
      DB_PASSWORD: password
    # On n'ouvre plus de "ports", on "expose" uniquement en interne pour Caddy
    expose:
      - "8080"

  frontend:
    image: ghcr.io/mariusdev80/citatio/frontend:latest
    container_name: citatio-front
    expose:
      - "80"

  gateway:
    image: caddy:latest
    container_name: citatio-gateway
    restart: always
    ports:
      - "80:80"     # HTTP (pour redirection automatique)
      - "443:443"   # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    depends_on:
      - frontend
      - backend