spring.application.name=u1-communication

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:citatio_u1_db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
