-- Premier schema du blog (citatio_u2_db).
--
-- SQL volontairement commun a Postgres et a H2 en mode PostgreSQL : les tests
-- rejouent cette migration telle quelle, c'est ce qui la verifie avant le
-- deploiement. Pas de type propre a Postgres (text[], enum natif) pour cette
-- raison.

CREATE TABLE article (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Adresse publique de l'article (/blog/<slug>). Unique : deux articles de
    -- meme titre recoivent un suffixe numerique cote service.
    slug               VARCHAR(90)    NOT NULL,
    title              VARCHAR(140)   NOT NULL,
    -- Chapeau : affiche dans la liste et repris en meta description.
    excerpt            VARCHAR(300)   NOT NULL,
    -- VARCHAR borne plutot que TEXT : H2 traduit TEXT en CLOB, que la
    -- validation Hibernate refuse pour un String.
    body               VARCHAR(50000) NOT NULL,
    author             VARCHAR(80)    NOT NULL,
    -- Les deux colonnes sont nulles ensemble : un article sans image.
    image_alt          VARCHAR(200),
    image_content_type VARCHAR(20),
    published_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_article_slug UNIQUE (slug)
);

-- La liste est toujours lue du plus recent au plus ancien.
CREATE INDEX idx_article_published_at ON article (published_at);

CREATE TABLE article_category (
    article_id BIGINT      NOT NULL,
    category   VARCHAR(30) NOT NULL,
    CONSTRAINT pk_article_category PRIMARY KEY (article_id, category),
    CONSTRAINT fk_article_category_article
        FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE
);

-- L'image vit dans sa propre table : la liste des articles ne charge jamais
-- ses octets, et la table article reste legere a parcourir.
-- En base plutot que sur disque : aucun volume ni aucune regle de gateway a
-- ajouter, et la sauvegarde de la base emporte les images avec les articles.
CREATE TABLE article_image (
    article_id BIGINT NOT NULL,
    content    BYTEA  NOT NULL,
    CONSTRAINT pk_article_image PRIMARY KEY (article_id),
    CONSTRAINT fk_article_image_article
        FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE
);
