spring.application.name=citatio-backend

# Connexion à la base de données (Les variables seront injectées par Docker)
spring.datasource.url=jdbc:postgresql://${DB_HOST:database}:5432/${DB_NAME:citatio_db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Pour voir les requêtes SQL dans les logs (utile au début)
spring.jpa.show-sql=true